-- =============================================================================
-- CodeJudge – lược đồ cơ sở dữ liệu (PostgreSQL ≥ 14)
--
-- Quy ước:
--   * Khóa chính BIGINT IDENTITY (BY DEFAULT để seed được id cố định); workers dùng
--     mã chuỗi do Worker tự đặt (worker-1, ...).
--   * Thời gian luôn là TIMESTAMPTZ; API đổi sang epoch ms cho frontend.
--   * Trạng thái/nhãn dùng VARCHAR + CHECK thay vì ENUM của PostgreSQL: map thẳng với
--     @Enumerated(EnumType.STRING) của JPA và thêm giá trị mới không cần ALTER TYPE.
--   * Hàng đợi FIFO sống trong RAM của Master; DB là nguồn sự thật để khôi phục hàng
--     đợi khi Master khởi động lại (xem chỉ mục ix_submissions_pending).
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Tiện ích: tự cập nhật updated_at
-- -----------------------------------------------------------------------------
CREATE FUNCTION set_updated_at() RETURNS trigger
    LANGUAGE plpgsql AS
$$
BEGIN
    NEW.updated_at := now();
    RETURN NEW;
END;
$$;

-- -----------------------------------------------------------------------------
-- Người dùng & phiên đăng nhập
-- -----------------------------------------------------------------------------
CREATE TABLE users (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username       VARCHAR(32)  NOT NULL,             -- MSSV (B20DCCN001) hoặc 'admin'
    full_name      VARCHAR(100) NOT NULL,
    role           VARCHAR(16)  NOT NULL DEFAULT 'STUDENT'
                   CHECK (role IN ('STUDENT', 'ADMIN')),
    password_hash  VARCHAR(100),                      -- bcrypt; thí sinh đăng nhập bằng MSSV nên NULL
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    last_login_at  TIMESTAMPTZ,
    CONSTRAINT ck_users_admin_password CHECK (role <> 'ADMIN' OR password_hash IS NOT NULL),
    CONSTRAINT ck_users_student_code   CHECK (role <> 'STUDENT' OR username ~ '^[A-Z][0-9]{2}[A-Z]{4}[0-9]{3}$')
);
CREATE UNIQUE INDEX ux_users_username ON users (upper(username));

COMMENT ON TABLE  users IS 'Thí sinh (đăng nhập bằng MSSV + họ tên) và quản trị viên (mật khẩu).';
COMMENT ON COLUMN users.username IS 'MSSV viết hoa với thí sinh; đây là userId mà API trả về.';

-- Bearer token: chỉ lưu SHA-256 của token, lộ DB cũng không dùng lại được token.
CREATE TABLE sessions (
    token_hash   BYTEA        PRIMARY KEY CHECK (octet_length(token_hash) = 32),
    user_id      BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    expires_at   TIMESTAMPTZ  NOT NULL,
    revoked_at   TIMESTAMPTZ,
    client_ip    INET,
    user_agent   VARCHAR(255)
);
CREATE INDEX ix_sessions_user ON sessions (user_id);
CREATE INDEX ix_sessions_expires ON sessions (expires_at) WHERE revoked_at IS NULL;

-- -----------------------------------------------------------------------------
-- Đề bài & bộ test
-- -----------------------------------------------------------------------------
CREATE TABLE problems (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title            VARCHAR(200) NOT NULL,
    difficulty       VARCHAR(8)   NOT NULL DEFAULT 'easy'
                     CHECK (difficulty IN ('easy', 'medium', 'hard')),
    tags             TEXT[]       NOT NULL DEFAULT '{}',
    statement        TEXT         NOT NULL,           -- Markdown
    input_spec       TEXT         NOT NULL DEFAULT '',
    output_spec      TEXT         NOT NULL DEFAULT '',
    time_limit_ms    INTEGER      NOT NULL DEFAULT 1000 CHECK (time_limit_ms BETWEEN 100 AND 10000),
    memory_limit_mb  INTEGER      NOT NULL DEFAULT 256  CHECK (memory_limit_mb BETWEEN 16 AND 1024),
    checker          VARCHAR(16)  NOT NULL DEFAULT 'lines'
                     CHECK (checker IN ('lines', 'tokens', 'exact')),
    is_public        BOOLEAN      NOT NULL DEFAULT TRUE,  -- FALSE: chỉ dùng trong kỳ thi / bản nháp
    created_by       BIGINT       REFERENCES users (id) ON DELETE SET NULL,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    deleted_at       TIMESTAMPTZ                       -- xóa mềm: bài nộp cũ vẫn tham chiếu được
);
CREATE INDEX ix_problems_tags ON problems USING gin (tags);
CREATE INDEX ix_problems_active ON problems (id) WHERE deleted_at IS NULL;
CREATE TRIGGER trg_problems_updated_at BEFORE UPDATE ON problems
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

COMMENT ON COLUMN problems.checker IS 'Cách so output, khớp với judgement/checker.py.';
COMMENT ON COLUMN problems.deleted_at IS 'Admin "xóa" đề = đặt deleted_at; frontend hiển thị "(đã xoá)".';

-- Ví dụ (is_sample) hiển thị trong đề và cũng được chấm; test ẩn chỉ gửi cho Worker.
CREATE TABLE test_cases (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    problem_id       BIGINT   NOT NULL REFERENCES problems (id) ON DELETE CASCADE,
    position         SMALLINT NOT NULL CHECK (position >= 1),   -- thứ tự chấm, = index trong kết quả
    input            TEXT     NOT NULL,
    expected_output  TEXT     NOT NULL,
    is_sample        BOOLEAN  NOT NULL DEFAULT FALSE,
    CONSTRAINT uq_test_cases_position UNIQUE (problem_id, position) DEFERRABLE INITIALLY DEFERRED
);

COMMENT ON CONSTRAINT uq_test_cases_position ON test_cases IS
    'DEFERRABLE để admin đổi thứ tự test trong một transaction.';

-- -----------------------------------------------------------------------------
-- Kỳ thi (thể thức ICPC)
-- -----------------------------------------------------------------------------
CREATE TABLE contests (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title              VARCHAR(200) NOT NULL,
    description        TEXT         NOT NULL DEFAULT '',
    start_at           TIMESTAMPTZ  NOT NULL,
    end_at             TIMESTAMPTZ  NOT NULL,
    penalty_minutes    SMALLINT     NOT NULL DEFAULT 20 CHECK (penalty_minutes >= 0),
    created_by         BIGINT       REFERENCES users (id) ON DELETE SET NULL,
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_contests_window CHECK (end_at > start_at)
);
CREATE INDEX ix_contests_start ON contests (start_at);
CREATE TRIGGER trg_contests_updated_at BEFORE UPDATE ON contests
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

COMMENT ON COLUMN contests.penalty_minutes IS 'Phút phạt cho mỗi lần nộp sai trước AC (CE/SEC không tính).';

CREATE TABLE contest_problems (
    contest_id   BIGINT     NOT NULL REFERENCES contests (id) ON DELETE CASCADE,
    problem_id   BIGINT     NOT NULL REFERENCES problems (id),
    label        VARCHAR(2) NOT NULL CHECK (label ~ '^[A-Z]{1,2}$'),   -- A, B, C, ...
    PRIMARY KEY (contest_id, problem_id),
    CONSTRAINT uq_contest_problems_label UNIQUE (contest_id, label) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX ix_contest_problems_problem ON contest_problems (problem_id);

CREATE TABLE contest_participants (
    contest_id     BIGINT      NOT NULL REFERENCES contests (id) ON DELETE CASCADE,
    user_id        BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    registered_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (contest_id, user_id)
);
CREATE INDEX ix_contest_participants_user ON contest_participants (user_id);

-- -----------------------------------------------------------------------------
-- Cụm máy chấm
-- -----------------------------------------------------------------------------
-- Trạng thái "sống" (heartbeat 5s) nằm trong RAM của Master; bảng này chỉ cập nhật khi
-- Worker đăng ký / mất kết nối / chấm xong bài, để trang Admin và báo cáo có lịch sử.
CREATE TABLE workers (
    id                 VARCHAR(64)  PRIMARY KEY,         -- workerId trong OP_WORKER_REGISTER
    address            VARCHAR(64),                      -- ip:port lần kết nối gần nhất
    hostname           VARCHAR(255),
    version            VARCHAR(32),
    compiler           VARCHAR(255),
    sandbox            VARCHAR(32),
    status             VARCHAR(8)   NOT NULL DEFAULT 'DEAD'
                       CHECK (status IN ('IDLE', 'BUSY', 'DEAD')),
    completed_count    INTEGER      NOT NULL DEFAULT 0,
    register_payload   JSONB,                            -- toàn bộ payload REGISTER để tra cứu
    first_seen_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    connected_at       TIMESTAMPTZ,
    disconnected_at    TIMESTAMPTZ,
    last_heartbeat_at  TIMESTAMPTZ
);

-- -----------------------------------------------------------------------------
-- Bài nộp
-- -----------------------------------------------------------------------------
CREATE TABLE submissions (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1001) PRIMARY KEY,
    user_id           BIGINT      NOT NULL REFERENCES users (id),
    problem_id        BIGINT      NOT NULL REFERENCES problems (id),
    contest_id        BIGINT,                             -- NULL = luyện tập
    language          VARCHAR(16) NOT NULL DEFAULT 'cpp17' CHECK (language IN ('cpp17')),
    source_code       TEXT        NOT NULL CHECK (octet_length(source_code) <= 65536),

    -- Giới hạn chụp lại lúc nộp: admin sửa đề sau đó không làm sai lệch kết quả cũ / lần chấm lại.
    time_limit_ms     INTEGER     NOT NULL,
    memory_limit_mb   INTEGER     NOT NULL,

    status            VARCHAR(12) NOT NULL DEFAULT 'IN_QUEUE'
                      CHECK (status IN ('IN_QUEUE', 'COMPILING', 'TESTING', 'FINISHED', 'FAILED')),
    verdict           VARCHAR(3)  CHECK (verdict IN ('AC', 'WA', 'TLE', 'MLE', 'RTE', 'CE', 'SEC')),
    score             SMALLINT    CHECK (score BETWEEN 0 AND 100),
    time_ms           INTEGER,                            -- max CPU time qua các test
    memory_kb         INTEGER,                            -- max RSS qua các test
    passed_tests      SMALLINT,
    total_tests       SMALLINT,
    compile_log       TEXT,
    security_message  TEXT,
    error_message     TEXT,                               -- lý do FAILED (hết 3 lần Failover, lỗi máy chấm)

    worker_id         VARCHAR(64) REFERENCES workers (id) ON DELETE SET NULL,
    attempts          SMALLINT    NOT NULL DEFAULT 0 CHECK (attempts BETWEEN 0 AND 3),
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    started_at        TIMESTAMPTZ,                        -- lần OP_TASK_ASSIGN gần nhất
    finished_at       TIMESTAMPTZ,

    -- Bài nộp trong kỳ thi phải là bài thuộc kỳ thi đó (MATCH SIMPLE: bỏ qua khi contest_id NULL).
    CONSTRAINT fk_submissions_contest_problem FOREIGN KEY (contest_id, problem_id)
        REFERENCES contest_problems (contest_id, problem_id),
    CONSTRAINT ck_submissions_verdict_when_finished
        CHECK ((status = 'FINISHED') = (verdict IS NOT NULL)),
    CONSTRAINT ck_submissions_finished_at
        CHECK ((status IN ('FINISHED', 'FAILED')) = (finished_at IS NOT NULL))
);
CREATE INDEX ix_submissions_user ON submissions (user_id, id DESC);
CREATE INDEX ix_submissions_problem ON submissions (problem_id, id DESC);
CREATE INDEX ix_submissions_contest ON submissions (contest_id, created_at) WHERE contest_id IS NOT NULL;
CREATE INDEX ix_submissions_verdict ON submissions (verdict, id DESC) WHERE verdict IS NOT NULL;
-- Khôi phục hàng đợi FIFO khi Master khởi động lại: các bài chưa xong, theo thứ tự nộp.
CREATE INDEX ix_submissions_pending ON submissions (id) WHERE status IN ('IN_QUEUE', 'COMPILING', 'TESTING');

COMMENT ON COLUMN submissions.status IS
    'IN_QUEUE → COMPILING → TESTING → FINISHED; FAILED khi Failover quá 3 lần hoặc lỗi máy chấm.';
COMMENT ON COLUMN submissions.attempts IS 'Số lần đã giao cho Worker (Failover tối đa 3 lần).';

-- Bài nộp trong kỳ thi: thí sinh đã đăng ký và nộp trong thời gian thi.
CREATE FUNCTION check_contest_submission() RETURNS trigger
    LANGUAGE plpgsql AS
$$
DECLARE
    c contests%ROWTYPE;
BEGIN
    IF NEW.contest_id IS NULL THEN
        RETURN NEW;
    END IF;
    SELECT * INTO c FROM contests WHERE id = NEW.contest_id;
    IF NEW.created_at < c.start_at OR NEW.created_at >= c.end_at THEN
        RAISE EXCEPTION 'Kỳ thi % không trong thời gian làm bài', NEW.contest_id
            USING ERRCODE = 'check_violation';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM contest_participants p
                   WHERE p.contest_id = NEW.contest_id AND p.user_id = NEW.user_id) THEN
        RAISE EXCEPTION 'Người dùng % chưa đăng ký kỳ thi %', NEW.user_id, NEW.contest_id
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER trg_submissions_contest BEFORE INSERT ON submissions
    FOR EACH ROW EXECUTE FUNCTION check_contest_submission();

-- Kết quả từng test (payload "tests" trong OP_TASK_RESULT).
CREATE TABLE submission_test_results (
    submission_id   BIGINT      NOT NULL REFERENCES submissions (id) ON DELETE CASCADE,
    test_index      SMALLINT    NOT NULL CHECK (test_index >= 1),
    test_case_id    BIGINT      REFERENCES test_cases (id) ON DELETE SET NULL,
    status          VARCHAR(8)  NOT NULL
                    CHECK (status IN ('AC', 'WA', 'TLE', 'MLE', 'RTE', 'SKIPPED')),
    time_ms         INTEGER,
    memory_kb       INTEGER,
    output_preview  TEXT,                                -- Worker đã cắt còn ≤ 4 KB
    stderr_preview  TEXT,
    exit_code       INTEGER,
    signal          VARCHAR(16),
    detail          VARCHAR(255),
    PRIMARY KEY (submission_id, test_index)
);

-- Dòng thời gian của bài nộp (trang chi tiết hiển thị cả Failover).
CREATE TABLE submission_events (
    id             BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    submission_id  BIGINT      NOT NULL REFERENCES submissions (id) ON DELETE CASCADE,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    event          VARCHAR(12) NOT NULL
                   CHECK (event IN ('IN_QUEUE', 'ASSIGNED', 'COMPILING', 'TESTING', 'SCAN',
                                    'REJECTED', 'REQUEUED', 'FINISHED', 'FAILED', 'REJUDGE')),
    worker_id      VARCHAR(64) REFERENCES workers (id) ON DELETE SET NULL,
    attempt        SMALLINT,
    note           TEXT
);
CREATE INDEX ix_submission_events_submission ON submission_events (submission_id, id);

-- -----------------------------------------------------------------------------
-- Nhật ký Master (trang Admin)
-- -----------------------------------------------------------------------------
CREATE TABLE system_logs (
    id             BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    level          VARCHAR(8)  NOT NULL CHECK (level IN ('info', 'success', 'warning', 'error')),
    message        TEXT        NOT NULL,
    worker_id      VARCHAR(64) REFERENCES workers (id) ON DELETE SET NULL,
    submission_id  BIGINT      REFERENCES submissions (id) ON DELETE SET NULL
);
CREATE INDEX ix_system_logs_created ON system_logs (created_at DESC);

-- =============================================================================
-- View phục vụ API
-- =============================================================================

-- GET /api/problems: totalSubmissions, acceptedSubmissions, testCount.
CREATE VIEW v_problem_stats AS
SELECT p.id                                                    AS problem_id,
       (SELECT count(*) FROM test_cases t WHERE t.problem_id = p.id) AS test_count,
       count(s.id)                                             AS total_submissions,
       count(s.id) FILTER (WHERE s.verdict = 'AC')             AS accepted_submissions,
       count(DISTINCT s.user_id) FILTER (WHERE s.verdict = 'AC') AS solved_users
FROM problems p
LEFT JOIN submissions s ON s.problem_id = p.id AND s.status = 'FINISHED'
GROUP BY p.id;

-- Ô (thí sinh, bài) của bảng xếp hạng chung: điểm cao nhất, số lần nộp tới khi AC.
CREATE VIEW v_user_problem_best AS
WITH finished AS (
    SELECT s.user_id, s.problem_id, s.score, s.verdict, s.created_at,
           min(s.created_at) FILTER (WHERE s.verdict = 'AC')
               OVER (PARTITION BY s.user_id, s.problem_id) AS first_ac_at
    FROM submissions s
    JOIN users u ON u.id = s.user_id AND u.role = 'STUDENT'
    WHERE s.status = 'FINISHED'
)
SELECT user_id,
       problem_id,
       max(score)                                                    AS best_score,
       count(*) FILTER (WHERE first_ac_at IS NULL OR created_at <= first_ac_at) AS tries,
       count(*)                                                      AS attempts,
       coalesce(bool_or(verdict = 'AC'), FALSE)                      AS solved,
       min(first_ac_at)                                              AS first_ac_at
FROM finished
GROUP BY user_id, problem_id;

-- GET /api/leaderboard: tổng điểm = tổng điểm cao nhất mỗi bài.
CREATE VIEW v_leaderboard AS
SELECT rank() OVER (ORDER BY sum(b.best_score) DESC, count(*) FILTER (WHERE b.solved) DESC,
                             max(b.first_ac_at) ASC NULLS LAST) AS rank,
       u.id                                  AS user_id,
       u.username,
       u.full_name,
       count(*) FILTER (WHERE b.solved)      AS solved,
       sum(b.best_score)                     AS score,
       sum(b.attempts)                       AS attempts,
       max(b.first_ac_at)                    AS last_ac_at
FROM v_user_problem_best b
JOIN users u ON u.id = b.user_id
GROUP BY u.id;

-- GET /api/contests/:id/standings – ô ICPC (thí sinh, bài) trong một kỳ thi.
CREATE VIEW v_contest_cells AS
WITH subs AS (
    SELECT s.contest_id, s.user_id, s.problem_id, s.status, s.verdict, s.created_at,
           min(s.created_at) FILTER (WHERE s.verdict = 'AC')
               OVER (PARTITION BY s.contest_id, s.user_id, s.problem_id) AS first_ac_at
    FROM submissions s
    JOIN contests c ON c.id = s.contest_id
    WHERE s.created_at < c.end_at
)
SELECT sb.contest_id,
       sb.user_id,
       sb.problem_id,
       cp.label,
       coalesce(bool_or(sb.verdict = 'AC'), FALSE)                           AS solved,
       count(*) FILTER (WHERE sb.status = 'FINISHED' AND sb.verdict NOT IN ('AC', 'CE', 'SEC')
                          AND (sb.first_ac_at IS NULL OR sb.created_at < sb.first_ac_at)) AS wrong,
       count(*) FILTER (WHERE sb.status NOT IN ('FINISHED', 'FAILED')
                          AND (sb.first_ac_at IS NULL OR sb.created_at < sb.first_ac_at)) AS pending,
       floor(extract(epoch FROM min(sb.first_ac_at) - c.start_at) / 60)::int AS solve_minute,
       min(sb.first_ac_at)                                                   AS first_ac_at,
       -- Người giải bài này sớm nhất trong kỳ thi (ô "first blood" trên bảng xếp hạng).
       coalesce(min(sb.first_ac_at) = min(min(sb.first_ac_at))
                    OVER (PARTITION BY sb.contest_id, sb.problem_id), FALSE) AS first_solve
FROM subs sb
JOIN contests c          ON c.id = sb.contest_id
JOIN contest_problems cp ON cp.contest_id = sb.contest_id AND cp.problem_id = sb.problem_id
GROUP BY sb.contest_id, sb.user_id, sb.problem_id, cp.label, c.start_at;

-- Bảng xếp hạng ICPC: số bài AC giảm dần, rồi tổng phút phạt tăng dần.
-- Thí sinh đã đăng ký nhưng chưa nộp vẫn có một dòng (0 bài, 0 phút).
CREATE VIEW v_contest_standings AS
WITH totals AS (
    SELECT p.contest_id,
           p.user_id,
           count(*) FILTER (WHERE cc.solved)                                       AS solved,
           coalesce(sum(cc.solve_minute + cc.wrong * c.penalty_minutes)
                    FILTER (WHERE cc.solved), 0)                                    AS penalty
    FROM contest_participants p
    JOIN contests c ON c.id = p.contest_id
    LEFT JOIN v_contest_cells cc ON cc.contest_id = p.contest_id AND cc.user_id = p.user_id
    GROUP BY p.contest_id, p.user_id
)
SELECT t.contest_id,
       rank() OVER (PARTITION BY t.contest_id ORDER BY t.solved DESC, t.penalty ASC) AS rank,
       t.user_id,
       u.username,
       u.full_name,
       t.solved,
       t.penalty
FROM totals t
JOIN users u ON u.id = t.user_id;
